apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c", "echo Hello Kubernetes! && sleep 3600" ]
      resources:
        requests:
          memory: "64Mi"
          cpu: "0.5"
